/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaandigitalsipa;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB 1 PC 16
 */
public class adminn extends javax.swing.JInternalFrame {

    /**
     * Creates new form adminn
     */
    public adminn() {
        initComponents();
         muatTabel();
    }
    private void muatTabel(){
        String jk="";
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        //kosongkan model
        model.getDataVector().removeAllElements();
        //buat query ambil data
        String sql = "select * from admin";
        //buat objek model database
        ModelDataBase md = new ModelDataBase();
        ResultSet rs = md.ambilData(sql);
        try {
            while(rs.next()){
                Vector baris = new Vector();
                baris.add(rs.getInt("id"));
                baris.add(rs.getString("namalengkap"));
                baris.add(rs.getString("password"));
                baris.add(rs.getString("username"));                
                baris.add(rs.getString("jeniskelamin"));
                baris.add(rs.getString("noHp"));
                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(adminn.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    
     void kosong(){
        user.setText("");
        pas.setText("");
        namleng.setText("");
        buttonGroup1.clearSelection();
        hp.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namleng = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cwk = new javax.swing.JRadioButton();
        cw = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        hp = new javax.swing.JTextField();
        sim = new javax.swing.JButton();
        hap = new javax.swing.JButton();
        bat = new javax.swing.JButton();
        edi = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Password", "Username", "Jenis kelamin", "No Hp"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Admin");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Password");

        jLabel4.setText("Username");

        jLabel5.setText("Jenis  kelamin");

        buttonGroup1.add(cwk);
        cwk.setText("laki-laki");
        cwk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwkActionPerformed(evt);
            }
        });

        buttonGroup1.add(cw);
        cw.setText("Perempuan");
        cw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwActionPerformed(evt);
            }
        });

        jLabel6.setText("No Hp");

        sim.setText("Simpan");
        sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simMouseClicked(evt);
            }
        });

        hap.setText("Hapus");

        bat.setText("Batal");

        edi.setText("Edit");
        edi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ediMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cwk)
                                .addGap(18, 18, 18)
                                .addComponent(cw)))))
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namleng, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hap, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(edi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namleng, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cwk)
                    .addComponent(cw))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hap)
                    .addComponent(sim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edi)
                    .addComponent(bat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cwkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cwkActionPerformed

    private void cwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cwActionPerformed

    private void simMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseClicked
        // TODO add your handling code here:
        String u = user.getText();
        String p = pas.getText();
        String nm = namleng.getText();
        String jk = "";
        if(cwk.isSelected()){
            jk = cwk.getText();
        }else if(cw.isSelected()){
            jk = cw.getText();
        }
       
        String n = hp.getText();
        String sql = "insert into admin(username,password,namalengkap,jeniskelamin,noHp) values('"+u+"','"+p+"','"+nm+"','"+jk+"','"+n+"')";
       
        ModelDataBase kn = new ModelDataBase();
        if(kn.rubahData(sql)){
           status.setText("Data Berhasil Ditambahkan");
           muatTabel();
        }else{
            status.setText("Data Gagal Ditambahkan");
        }
        
        kosong();
    }//GEN-LAST:event_simMouseClicked

    private void ediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ediMouseClicked
        // TODO add your handling code here:
        int no_baris = tbl.getSelectedRow();
        String kode = tbl.getValueAt(no_baris, 0).toString();
        String u = user.getText();
        String p = pas.getText();
        String nm = namleng.getText();
        String jk = "";
        if(cwk.isSelected()){
            jk = cwk.getText();
        }else if(cw.isSelected()){
            jk = cw.getText();
        }
         String n = hp.getText();
        //buat query update database
        String sql = "update kategoribuku set username='"+u+"', password='"+p+"', namalengkap='"+nm+"', jeniskelamin='"+jk+"', noHp='"+n+"' where id="+kode;
        //periksa update apakah berhasil
         ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil diperbaharui");
            muatTabel();
        }else{
            status.setText("data gagal diperbaharui");
        }
        kosong();
    }//GEN-LAST:event_ediMouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
         int no_baris = tbl.getSelectedRow();
        // isi text
        namleng.setText(tbl.getValueAt(no_baris, 1).toString());
        pas.setText(tbl.getValueAt(no_baris, 2).toString());
        user.setText(tbl.getValueAt(no_baris, 3).toString());
        hp.setText(tbl.getValueAt(no_baris, 6).toString());
    }//GEN-LAST:event_tblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cw;
    private javax.swing.JRadioButton cwk;
    private javax.swing.JButton edi;
    private javax.swing.JButton hap;
    private javax.swing.JTextField hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namleng;
    private javax.swing.JTextField pas;
    private javax.swing.JButton sim;
    private javax.swing.JLabel status;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
