/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaandigitalsipa;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB 1 PC 16
 */
public class buku extends javax.swing.JInternalFrame {

    /**
     * Creates new form buku
     */
    public buku() {
        initComponents();
        muatTabel();
        muatkategori();
    }
    private  void muatTabel(){
        DefaultTableModel model = (DefaultTableModel) tb.getModel();
        model.getDataVector().removeAllElements();
        String sql = "select*from buku";
        
        ModelDataBase md = new ModelDataBase();
        ResultSet rs = md.ambilData(sql);
        
        try {
            while(rs.next()){
                Vector baris = new Vector();
                baris.add(rs.getInt("id"));
                baris.add(rs.getString("judul"));
                baris.add(rs.getString("penulis"));
                baris.add(rs.getString("penerbit"));
                baris.add(rs.getString("tahunterbit"));
                baris.add(rs.getString("stok"));
                baris.add(rs.getString("kategori_id"));
                model.addRow(baris);
            }
        } catch (Exception e) {
            Logger.getLogger(buku.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }
    
     public void  muatkategori(){
        ModelDataBase model = new ModelDataBase();
        String sql = "select * from kategoribuku";
        ResultSet rs = model.ambilData(sql);
        try {
            while (rs.next()) {                
                kat.addItem(String.valueOf(rs.getInt("id")));
            }
        } catch (SQLException e) {
            Logger.getLogger(buku.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
     void kosong(){
        jud.setText("");
        pen.setText("");
        pener.setText("");
        tat.setText("");
        stok.setText("");
        kat.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jud = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pener = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bat = new javax.swing.JButton();
        edt = new javax.swing.JButton();
        sim = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        hap = new javax.swing.JButton();
        tat = new javax.swing.JTextField();
        kat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        status = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Judul");

        jLabel2.setText("Penulis");

        jLabel3.setText("Penerbit");

        jLabel4.setText("Tahun Terbit");

        jLabel5.setText("Stok");

        jLabel6.setText("Kategori");

        bat.setText("Batal");
        bat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batMouseClicked(evt);
            }
        });

        edt.setText("Edit");
        edt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edtMouseClicked(evt);
            }
        });

        sim.setText("Simpan");
        sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simMouseClicked(evt);
            }
        });

        jLabel7.setText("BUKU");

        hap.setText("Hapus");
        hap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sim, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(hap, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jud)
                                    .addComponent(jLabel2)
                                    .addComponent(pen)
                                    .addComponent(jLabel3)
                                    .addComponent(pener)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(stok, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(tat)
                                            .addComponent(kat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim)
                    .addComponent(hap))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt)
                    .addComponent(bat))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Judul", "Penulis", "Penerbit", "Tahun Terbit", "Stok", "Kategori"
            }
        ));
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseClicked
        // TODO add your handling code here:
        String jd = jud.getText();
        String pn = pen.getText();
        String pr = pener.getText();
        String th = tat.getText();
        String st = stok.getText();
        String kt = (String) kat.getSelectedItem();
        String sql = "insert into buku(judul, penulis, penerbit, tahunterbit, stok, kategori_id) value('"+jd+"','"+pn+"','"+pr+"','"+th+"','"+st+"','"+kt+"')";
        ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil ditambahkan");
            muatTabel();
        }else{
            status.setText("data gagal ditambahkan");
        }
    }//GEN-LAST:event_simMouseClicked

    private void edtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edtMouseClicked
        // TODO add your handling code here:
        int no_baris = tb.getSelectedRow();
        String kode = tb.getValueAt(no_baris, 0).toString();
        String jd = jud.getText();
        String pn = pen.getText();
        String pr = pener.getText();
        String th = tat.getText();
        String st = stok.getText();
        String kt = (String) kat.getSelectedItem();
        //buat query update database
        String sql = "update kategoribuku set judul='"+jd+"',penulis='"+pn+"',penerbit='"+pr+"',tahunterbit='"+th+"',stok='"+st+"',kategori_id='"+kt+"' where id="+kode;
        //periksa update apakah berhasil
         ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil diperbaharui");
            muatTabel();
        }else{
            status.setText("data gagal diperbaharui");
        }
        kosong();
    }//GEN-LAST:event_edtMouseClicked

    private void hapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapMouseClicked
        // TODO add your handling code here:
        int no_baris = tb.getSelectedRow();
        String kode = tb.getValueAt(no_baris, 0).toString();
        //buat query update database
        String sql = "delete  from buku where id="+kode;
        //periksa update apakah berhasil
         ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil dihapus");
            muatTabel();
        }else{
            status.setText("data gagal dihapus ");
        }
        kosong();
    }//GEN-LAST:event_hapMouseClicked

    private void batMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batMouseClicked
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_batMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bat;
    private javax.swing.JButton edt;
    private javax.swing.JButton hap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jud;
    private javax.swing.JComboBox<String> kat;
    private javax.swing.JTextField pen;
    private javax.swing.JTextField pener;
    private javax.swing.JButton sim;
    private javax.swing.JLabel status;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField tat;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
