/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaandigitalsipa;

import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB 1 PC 16
 */
public class Kategori extends javax.swing.JInternalFrame {

    /**
     * Creates new form Kategori
     */
    public Kategori() {
        initComponents();
        muatTabel();
    }
    
    private  void muatTabel(){
        DefaultTableModel model = (DefaultTableModel) t.getModel();
        model.getDataVector().removeAllElements();
        String sql = "select*from kategoribuku";
        
        ModelDataBase md = new ModelDataBase();
        ResultSet rs = md.ambilData(sql);
        
        try {
            while(rs.next()){
                Vector baris = new Vector();
                baris.add(rs.getInt("id"));
                baris.add(rs.getString("namakategori"));
                model.addRow(baris);
            }
        } catch (Exception e) {
            Logger.getLogger(Kategori.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }
    void kosong(){
        nam.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bat = new javax.swing.JButton();
        hap = new javax.swing.JButton();
        sim = new javax.swing.JButton();
        edi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        status = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nama Kategori");

        jLabel2.setText("Kategori");

        bat.setText("Batal");
        bat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batMouseClicked(evt);
            }
        });

        hap.setText("Hapus");
        hap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapMouseClicked(evt);
            }
        });
        hap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapActionPerformed(evt);
            }
        });

        sim.setText("Simpan");
        sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simMouseClicked(evt);
            }
        });

        edi.setText("Edit");
        edi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ediMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nam)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sim, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hap, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(edi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim)
                    .addComponent(hap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bat)
                    .addComponent(edi))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama kategori"
            }
        ));
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapActionPerformed

    private void simMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simMouseClicked
        // TODO add your handling code here:
        String namaK = nam.getText();
        String sql = "insert into kategoribuku(namakategori) value('"+namaK+"')";
        ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil ditambahkan");
            muatTabel();
        }else{
            status.setText("data gagal ditambahkan");
        }
    }//GEN-LAST:event_simMouseClicked

    private void ediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ediMouseClicked
        // TODO add your handling code here:
        int no_baris = t.getSelectedRow();
        String kode = t.getValueAt(no_baris, 0).toString();
        String namaK = nam.getText();
        //buat query update database
        String sql = "update kategoribuku set namakategori='"+namaK+"' where id="+kode;
        //periksa update apakah berhasil
         ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil diperbaharui");
            muatTabel();
        }else{
            status.setText("data gagal diperbaharui");
        }
        kosong();
    }//GEN-LAST:event_ediMouseClicked

    private void hapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapMouseClicked
        // TODO add your handling code here:
        int no_baris = t.getSelectedRow();
        String kode = t.getValueAt(no_baris, 0).toString();
        //buat query update database
        String sql = "delete  from Kategoribuku where id="+kode;
        //periksa update apakah berhasil
         ModelDataBase md = new ModelDataBase();
        if(md.rubahData(sql)){
            status.setText("data berhasil dihapus");
            muatTabel();
        }else{
            status.setText("data gagal dihapus ");
        }
        kosong();
    }//GEN-LAST:event_hapMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        int no_baris = t.getSelectedRow();
        // isi text
        nam.setText(t.getValueAt(no_baris, 1).toString());
    }//GEN-LAST:event_tMouseClicked

    private void batMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batMouseClicked
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_batMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bat;
    private javax.swing.JButton edi;
    private javax.swing.JButton hap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nam;
    private javax.swing.JButton sim;
    private javax.swing.JLabel status;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
